---

- name: configure lxd bridge
  template: src=lxd-bridge.j2 dest=/etc/default/lxd-bridge mode=0644 backup=yes
  notify:
    - restart lxd-bridge
  register: lxdconf

## FIXME! if executed in kitchen lxd, "Converge failed"
- name: force restart of lxd to have working network
  service: name=lxd state=restarted
  when: lxdconf.changed and (ansible_virtualization_type is not defined or not (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "kvm"))
## centos7/vagrant/virtualbox
  ignore_errors: true

- shell: "ps axu |grep [l]xd"
  changed_when: false
  register: ps
  ignore_errors: true
- debug: var=ps

## FIXME! idempotency issue on xenial: lxd fault at first run / lxd in lxd impact?
- debug: var=ansible_virtualization_type
- name: ensure lxd service is started and enabled
  service: name=lxd state=started enabled=yes
  when: (ansible_virtualization_type is not defined or not (ansible_virtualization_type == "lxc" or ansible_virtualization_type == "kvm"))
## centos7/vagrant/virtualbox
  ignore_errors: true

- shell: "ps axu |grep [l]xd"
  changed_when: false
  register: ps
  ignore_errors: true
- debug: var=ps

