---
- name: restart monit
  service: name=monit state=restarted
- name: restart lxd
  service: name=lxd state=restarted
- name: restart lxd-bridge
  service: name=lxd-bridge state=restarted
  when: ansible_distribution_release == 'xenial'

